### ISSUE TITLE
Wake Sequence

### ISSUE THREAD

**Issue by FluxIX** [bjoernkarmann/project_alias#12]
Instead of a wake word, a longer wake sequence would be useful (to prevent accidental activation).

**Comment by torekndsn** [comment]
Good point! Right now the wake sequence is a variable set to 1.6 sec in sound.py. This can be set to any number but it needs to be changed both in the backend and the frontend. However, if the sequence length is extended to e.g 3 seconds, and the actual wake word only takes up 2, it will create an extra wake-up delay of 1 sec. When the wake sequence is changed to a new length the model also needs to be retrained with data matching the same shape. To make this easier we made a dataset generator tool to record wav files via Alias and create examples from these wav files to train the neutral class: https://github.com/torekndsn/Dataset_generator-ProjectAlias

Here the recorded wav files will be turned into datasets with a desired wake sequence length , which is set as a variable
