### ISSUE TITLE
Memory Error when trying to install tensorflow

### ISSUE THREAD

**Issue by LazyG** [bjoernkarmann/project_alias#14]
For reference in case others experience the same issue I did when trying to install on a 2018-11-13-raspbian-stretch-full.img version of Raspian.

When trying to install tensorflow via command: sudo pip3 install tensorflow keras, I received the following memory error.

![tensorflowerror](https://user-images.githubusercontent.com/3107000/51442004-b6925f80-1c9d-11e9-9334-197b3164d0bf.png)

However, when I changed the command to the following it resolved the issue.
pip3 install --no-cache-dir tensorflow

**Comment by bjoernkarmann** [comment]
`pip3 install --no-cache-dir tensorflow` fixes this issue. To find more on related issues please refer to https://github.com/tensorflow/tensorflow/issues.

**Comment by rahulshyokand** [comment]
> `pip3 install --no-cache-dir tensorflow` fixes this issue. To find more on related issues please refer to https://github.com/tensorflow/tensorflow/issues.

Worked!

**Comment by shinkai-technology** [comment]
> `pip3 install --no-cache-dir tensorflow` fixes this issue. To find more on related issues please refer to https://github.com/tensorflow/tensorflow/issues.
Didn't work for me, but thanks

**Comment by tsei902** [comment]
worked as well for me!
