### ISSUE TITLE
Heads-up: etcher has been renamed to balenaEtcher

### ISSUE THREAD

**Issue by jdschuitemaker** [bjoernkarmann/project_alias#17]
The link to etcher.io is still working, but redirecting to https://www.balena.io/etcher/

**Comment by espoelstra** [comment]
Also use some caution with Etcher, many people have been reporting issues with dead USB drives or SD cards after using the more recent versions of Etcher, but it is really hard to determine from the Discourse posts about the issue whether it is user error or counterfeit flash memory or the tool itself.

**Comment by bjoernkarmann** [comment]
Hi, thanks for pointing it out! In our 2.0 version, we have linked to the correct belenaEtcher
