### ISSUE TITLE
[Idea] Add some sort of voice manipulation to prevent analysis

### ISSUE THREAD

**Issue by mrvnklm** [bjoernkarmann/project_alias#34]
Similar to #8, just with some constant sound playing while the device is listening, so it can still understand what you say, but without being able to detect mood, etc.
This would be easier to implement, because Alias only has to change the soundfile and volume level instead of analyzing your words and "text to speech" them.
I consider creating a pull request about this, but wanted to get your thoughts about that approach.

**Comment by bjoernkarmann** [comment]
Interesting idea! 
We have just launched a version 2.0 that gives you much more control of the functionalities. If you are still thinking of implementing your feature then it should not be too hard in this version. Hope to see your pull request
