### ISSUE TITLE
ALSA Problem

### ISSUE THREAD

**Issue by lle** [bjoernkarmann/project_alias#35]
After successfully installing all the packages as per the instruction, running "app.py" leads to the following error
`pi@raspberrypi:~/project_alias $ sudo python3 app.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib pcm_direct.c:1824:(_snd_pcm_direct_get_slave_ipc_offset) Invalid value for card
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from modules import connection
  File "/home/pi/project_alias/modules/connection.py", line 7, in <module>
    from modules import sound
  File "/home/pi/project_alias/modules/sound.py", line 14, in <module>
    pygame.mixer.init()
pygame.error: No available audio device
`

Not sure how to tackle the problem. Alsa is configured to select the peripheral "PCM". The HDMI cable is also not connected.

**Comment by torekndsn** [comment]
HI lle, 

We started working on a new version to make the install and use of Alisa much easier and better. 
It's now up on the main branch, and the whole project can now be installed from a single img file.

Best, Tore
