### ISSUE TITLE
White noise and building docs

### ISSUE THREAD

**Issue by dmkc** [bjoernkarmann/project_alias#4]
Very interesting project! I have 2 questions, not so much an issue:

1. Does the speaker make a white noise sound, or is it otherwise inaudible?
1. Do you have plans for instructions on how to put the parts together?

**Comment by berlincount** [comment]
Let's add to that: is there a 3D printer file for the cover? ;)

**Comment by bjoernkarmann** [comment]
Just updated the readme. You should find the link to the Instructables step-by-step guide. You will find the 3D assets there as well. Good luck!
