### ISSUE TITLE
Please provide `requirements.txt`

### ISSUE THREAD

**Issue by janniks** [bjoernkarmann/project_alias#41]
@bjoernkarmann @torekndsn 
Please provide your exact local pip dependencies. It looks like many people have a lot of problems with this...

It should be possible to save the dependencies to file with `pip freeze > requirements.txt` and them install exactly the same packages with `pip install -r requirements.txt` _(even if newer packages have come out in the meantime)_

**Comment by torekndsn** [comment]
Hi janniks, 

Thanks for the tip! 
We have been focusing on a second version with a lot of improvements to a new feature over the last months. We are happy to share that it's out now and comes with an image file for an easy install.

Best, Tore
