### ISSUE TITLE
2.0 Branch Image download link broken

### ISSUE THREAD

**Issue by bepstein** [bjoernkarmann/project_alias#44]
In the README for the 2.0 branch, it links to an image of the build.  That link leads to a 404.

https://github.com/bjoernkarmann/project_alias/blob/2.0

It would be awesome to get a fully installed image, I can't seem to get either branch working on my hardware.

Thanks,
Brian

**Comment by torekndsn** [comment]
Hi Brian, 
Version 2 is now the official branch, with an updated image file + instructions. 

Best, 
Tore

**Comment by bepstein** [comment]
Thank you Tore!
