### ISSUE TITLE
Alternative tiny speaker?

### ISSUE THREAD

**Issue by teijiIshida** [bjoernkarmann/project_alias#6]
Hello, I'm in the US and having a hard time finding the Visaton K 16 - 50 Ohm tiny speaker listed in your hardware requirement. Is it ok to use a different tiny speaker like the [Adafruit Mini Metal Speaker w/ Wires - 8 ohm 0.5W](https://www.amazon.com/dp/B00N4YSRRC/?coliid=I3VVHPBJQLJIA3&colid=NYQQVRYP5WZ9&psc=0&ref_=lv_ov_lig_dp_it)? Would the difference in watts and Ohm affect reliability?

**Comment by bjoernkarmann** [comment]
Hi, the speakers from Adafruit should not be a problem regarding sound or performance. But you have to be aware that the size of the speakers might not fit in the speaker holder I provided for the build. Nothing some glue can't fix. 

You might also need to adjust the volume in the code. To set the volume of the speaker you can change the line 32 in modules/sound.py = os.system('sudo amixer -c 1 sset Speaker 83') 

If the noise does not block out the assistant turn it up or if you can hear the noise your self turn it down.
