### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by cali-ern** [bjoernkarmann/project_alias#8]
Hi, fantastic project.

I have an idea to add to this project. That is adding a robotic voice (such as a "text to speech" free software) between the users and the he alexa/siri/whatever device. The aim is removing sensible data about the gender, sex or even the number of different persons than uses the device (where you can deduce the number of people that live in the house where the device is installed)

**Comment by bjoernkarmann** [comment]
Thanks for the proposal. This would indeed be an interesting feature. We are currently focusing our energy on improving the sound classification. But we would encourage anyone who is interested to create a pull request and add features they like. This project is meant to stay open-source and hopefully, together we can make this parasite better ;)
